# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0003_auto_20170905_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
